language: node_js
node_js: '8'
before_script: npm install -g wspackager
script: wspackager
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.pages.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com
  - secure: a956GpY+mxCdl0IvJuDM7mktMkB9rICZYSeSOiH5/Qf9XAFkpi0/AWHQ/JzWyDh6ucF2vnjK5C7BjwJ6R+Kv3cXHQR7AsvVsiEftfT0LoTzaPXnDO/Aun1BpEmy6/+9njajjBZGjJN52zCZum1Jz5nb4NjqmVWLdlrEJq+MVBAQIh/QrtzjKNWwtP6ybOFefdxzbUNn8xNOyGeKmWZtnU1qBb933o3pb3fpoC3q2nXPLquyi9GWHjDPEVb96xHlYqeJzn4At7bO5CqZmg8U6MyjpFLX+JajB2f1otdugPCLFSxjN70yrtq3FRdK2CH/Ugd0OMTZECSdLusziDv5emnT8S/VwD14Ba2exohgFKW22ux8gUR2efFN6pMvpLXpm9+gTYSqrzuyw8b3njSukMW2mu6jBonbGDjzhZ71x9e2Dxm1JgnweyiQExXHrYO7WW1Dks4+hdnpv/wnZ7ifqzcmx5KH+sl6QO7UhvoBUv8Pmm0CwaAjcgvurff2GSfIfn2OvOeEjIY8lngzs45zcq/cPl+S91cwIipHJKtV6+Iu6jUNZMlMSkyMLCjrXW7DqflSqWSch9tEPeRrILp7eVYTeNYIbbMhhkxrUUbXPobvjnoZN6e3TsI45okf8t5nUKmgF88nJ/YHiqmw4xvoDxf8pAWAt1QlR20Dsvlnoc+E=
  - secure: C3mcbu7rZWVIIOYBc/vAO8kDirAKen9ppv7N35ne7KnAj3h1RfmEPTgFEcWC90ANv24aIF7Dpwa5zvXkmBQWvNXwRnD4KA9sLJuJotLZOd+iZeuRasPw+TO8KUbflqr9WqDuLF3k4AA9h9BgxpMjMpRwioH2ihfUjVJtb1WxiMCMDO6J7VOAUr1EqFuUepCDXMENp+SwgQM1iyYNCYInh8fsASpK0iwXo6ysZ7vsw2gQVmxd+IYZqYez+0wyWFtZZZ6Qb+SeotNnKyuBLAY5V3kW+8APEm2MFgvNyC5/QTg4JexYNLcIwg1ZS42GWo2X7qHNs3PGhJKC14x9G+zbihaxW+E8esW8ZMVWh44Kiya0zxU9AuHXE+G03LVtDfMHzUTR3JafONTjGr/uucymaTpuoDdthRubZq889JbaddLlWgz/k8cUil9w7n2BPbkfFMS5RkNblVy+/5JIendyBOFMSQS1QJ925SY0lQog5F94Z8qnyCrNgja7XvJxEwKPIeKSBzLWvI4GB33AZFD3cOw+UujZ8a82re6Llrw9Upm/rEn0V8J5EY+OLCuadMeu2VN8ZfTvb6Zzc93EWs9w4LK1zFNHX0eaeedwBe6lDFdL5LB62N09jLpg8caNIFx9q0I/NbQD3E2dxza6xrd98QFH2TVTy1lGcv328vuSA0A=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
